import os
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

# Brand colors (matching the web app theme)
PRIMARY_COLOR = colors.HexColor("#6366F1")
SECONDARY_COLOR = colors.HexColor("#8B5CF6")
TEXT_DARK = colors.HexColor("#1F2937")
TEXT_GRAY = colors.HexColor("#6B7280")
GREEN = colors.HexColor("#059669")
RED = colors.HexColor("#DC2626")
LIGHT_BG = colors.HexColor("#F4F5FA")


def generate_resume_report(resume, result, output_path):
    """
    Generates a professional PDF report summarizing the ATS analysis
    of a resume, and saves it to output_path.
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        topMargin=50,
        bottomMargin=50,
        leftMargin=50,
        rightMargin=50,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"],
        textColor=PRIMARY_COLOR, fontSize=22, spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", parent=styles["Normal"],
        textColor=TEXT_GRAY, fontSize=10, spaceAfter=20
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"],
        textColor=TEXT_DARK, fontSize=13, spaceBefore=18, spaceAfter=8
    )
    body_style = ParagraphStyle(
        "BodyStyle", parent=styles["Normal"],
        textColor=TEXT_DARK, fontSize=10, leading=15
    )
    score_style = ParagraphStyle(
        "ScoreStyle", parent=styles["Title"],
        fontSize=36, alignment=1,
        textColor=(GREEN if result["score"] >= 70 else
                   colors.HexColor("#D97706") if result["score"] >= 40 else RED)
    )

    story = []

    # ---- Header ----
    story.append(Paragraph("CVPilot AI", title_style))
    story.append(Paragraph("ATS Resume Analysis Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB")))
    story.append(Spacer(1, 15))

    # ---- Resume Info ----
    story.append(Paragraph(f"<b>File:</b> {resume.original_filename}", body_style))
    story.append(Paragraph(
        f"<b>Analyzed on:</b> {datetime.utcnow().strftime('%d %B %Y, %I:%M %p')}",
        body_style
    ))
    story.append(Paragraph(f"<b>Word Count:</b> {result['word_count']}", body_style))

    # ---- Score ----
    story.append(Paragraph("ATS Compatibility Score", heading_style))
    story.append(Paragraph(f"{result['score']} / 100", score_style))
    story.append(Spacer(1, 15))

    # ---- Feedback ----
    story.append(Paragraph("Feedback & Suggestions", heading_style))
    for msg in result["feedback"]:
        story.append(Paragraph(f"• {msg}", body_style))
        story.append(Spacer(1, 4))

    # ---- Matched Keywords ----
    story.append(Paragraph(
        f"Matched Keywords ({len(result['matched_keywords'])})", heading_style
    ))
    if result["matched_keywords"]:
        matched_text = ", ".join(result["matched_keywords"])
        story.append(Paragraph(matched_text, ParagraphStyle(
            "MatchedStyle", parent=body_style, textColor=GREEN
        )))
    else:
        story.append(Paragraph("No matched keywords found.", body_style))

    # ---- Missing Keywords ----
    story.append(Paragraph(
        f"Missing Keywords ({len(result['missing_keywords'])})", heading_style
    ))
    if result["missing_keywords"]:
        missing_text = ", ".join(result["missing_keywords"])
        story.append(Paragraph(missing_text, ParagraphStyle(
            "MissingStyle", parent=body_style, textColor=RED
        )))
    else:
        story.append(Paragraph("No missing keywords — excellent coverage!", body_style))

    # ---- Footer ----
    story.append(Spacer(1, 30))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB")))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        "Generated by CVPilot AI — AI-Powered Resume Analyzer",
        ParagraphStyle("FooterStyle", parent=styles["Normal"], fontSize=8, textColor=TEXT_GRAY)
    ))

    doc.build(story)
    return output_path